on: push
jobs:
  Build_Push:
    runs-on: ubuntu-latest
    permissions:
     packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: silviavd02
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build an image
        run: docker build -t "my_first_app" .
        
      - name: Tag an image 
        run: docker tag my_first_app ghcr.io/silviavd02/dev-ops-exercises:app1 

      - name: Push Image to Dockerhub  
        run: docker push ghcr.io/silvavd02/dev-ops-exercises:app1



