on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone-down
        uses: actions/checkout@v3       
      - name: Build application
        run: docker build -t my-app .
      - name: Test
        run: docker run my-app 
      - name: Upload image
        uses: actions/upload-artifact@v3
        with: 
          name: my-app
          path: .


