on: push
jobs:
  Build_Push:
    runs-on: ubuntu-latest
    permissions:
     packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
      - name: Docker Login
        uses: docker/login-action@v3.0.0
        with:
          registry:  docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          logout : true

      - name: Build an image
        run: docker build -t "my_first_app" .
        
      - name: Tag an image 
        run: docker tag my_first_app silviavd02/dev-ops-exercises:latest

      - name: Push Image to Dockerhub  
        run: docker push silvavd02/dev-ops-exercises:latest



