on: push
jobs:
  Build_Push:
    runs-on: ubuntu-latest
    permissions:
     packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: silviavd02
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build an image
        run: docker build -t "my_first_app" .
        
      - name: Push an image to DockerHub
        run: docker push silvavd02/dev-ops-exercises



