on: push
jobs:
  SnykTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Run Snyk Security Check
        working-directory: ${{github.workspace}}/src
        run: |
          pip install -r requirements.txt
          npm install -g snyk
          snyk auth ${{secrets.SNYK_TOKEN}}
          snyk test


  Build_Push:
    runs-on: ubuntu-latest
    needs: [SnykTest]
    permissions:
     packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3 
        
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    
      - name: Build an image
        run: docker build -t "my_first_app" .
        
      - name: Tag an image 
        run: docker tag my_first_app silvavd02/dev-ops-exercises:latest

      - name: Push Image to Dockerhub  
        run: docker push silvavd02/dev-ops-exercises:latest







        



